aloha-agilex:
  file_path: "./assets/embodiments/aloha-agilex/"

piper:
  file_path: "./assets/embodiments/piper"

franka-panda:
  file_path: "./assets/embodiments/franka-panda/"

ARX-X5:
  file_path: "./assets/embodiments/ARX-X5"

ur5-wsg:
  file_path: "./assets/embodiments/ur5-wsg"

g1-omnipicker:
  file_path: "./assets/embodiments/g1-omnipicker/"
